---@meta

-- This file is auto-generated. Do not edit.
-- Generated by MoonGate Ultima Server

---@class TimerRegisterData
---@field Name string
---@field IntervalInSeconds number
---@field Callback function
---@field DelayInSeconds number
---@field IsRepeat boolean
---@field ToString fun(): string
---@field GetHashCode fun(): number
---@field Equals fun(obj: any): boolean
---@field Equals fun(other: TimerRegisterData): boolean
---@field <Clone>$ fun(): TimerRegisterData
---@field Deconstruct fun(Name: String&, IntervalInSeconds: Int32&, Callback: Action&, DelayInSeconds: Int32&, IsRepeat: Boolean&): nil

---@section Tables
include = {}
logger = {}
scheduler = {}
timers = {}

---@param message string
---@param args any[]
---@return nil
function logger.info(message, args) end

---@param message string
---@param args any[]
---@return nil
function logger.warn(message, args) end

---@param message string
---@param args any[]
---@return nil
function logger.error(message, args) end

---@param message string
---@param args any[]
---@return nil
function logger.debug(message, args) end

---@description Schedule a task to be run every x seconds
---@param name string
---@param seconds number
---@param callback function
---@return nil
function scheduler.add(name, seconds, callback) end

---@param file string
---@return nil
function include.file(file) end

---@param directory string
---@return nil
function include.dir(directory) end

---@description Register a timer
---@param register TimerRegisterData
---@return string
function timers.add(register) end

---@description Register a timer that repeats
---@param repeated TimerRegisterData
---@return string
function timers.add_repeated(repeated) end

---@description Register a timer that runs once
---@param register TimerRegisterData
---@return string
function timers.add_once(register) end

---@description Unregister a timer
---@param timerId string
---@return nil
function timers.delete(timerId) end

