---@meta

-- This file is auto-generated. Do not edit.
-- Generated by MoonGate Ultima Server

---@section Tables
logger = {}

---@param message string
---@return nil
function logger.info(message) end

